services:
  - type: web
    name: onefi-card-backend
    runtime: node
    buildCommand: npm install && npm run build:ci
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false